name: ci

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn install --immutable --ignore-scripts
      - run: yarn build
      - run: yarn test --ci
